trigger:
- main

pool:
  name: 'Default' # Replace with the name of your local agent pool

variables:
  MAVEN_HOME: 'C:\Users\belalahmad\Downloads\apache-maven-3.9.8-bin\apache-maven-3.9.8' # Replace with your actual local Maven path

steps:
- script: echo "$(MAVEN_HOME)"
  displayName: 'Show Maven Path'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx1024m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    mavenVersionOption: 'Path'
    mavenDirectory: '$(MAVEN_HOME)'  # Use your Maven installation path
    goals: 'clean install'

- script: mvn test -Dbrowser=localchrome
  displayName: 'Run Tests'

- script: mvn surefire-report:report-only
  displayName: 'Generate Test Report'

- script: mvn site -DgenerateReports=false
  displayName: 'Generate Site Report'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'target/site'
    artifactName: 'TestReport'
    publishLocation: 'pipeline'
  displayName: 'Publish HTML Test Report'
